zammadConfig:
  customVolumes:
    - name: custom-volume
      configMap:
        name: helm-tests
  customVolumeMounts:
    - name: custom-volume
      mountPath: /opt/zammad/lib/tasks/helm
      readOnly: true
