apiVersion: v1
data:
  root-password: emFtbWFkYWRtaW4=
  root-user: emFtbWFkYWRtaW4=
kind: Secret
metadata:
  name: minio-existing-secret
type: Opaque
---
apiVersion: v1
data:
  redis-password: cmVkaXM=
kind: Secret
metadata:
  name: redis-existing-secret
type: Opaque
---
apiVersion: v1
data:
  postgresql-password: emFtbWFk
kind: Secret
metadata:
  name: postgresql-existing-secret
type: Opaque
---
apiVersion: v1
data:
  elasticsearch-password: emFtbWFk
kind: Secret
metadata:
  name: elasticsearch-existing-secret
type: Opaque