chart-dirs: .
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - elastic=https://helm.elastic.co
check-version-increment: true
debug: true
helm-extra-args: --timeout 900s
target-branch: main
