---
chart-dirs: .
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
check-version-increment: true
debug: true
# upgrade: true # Causes issues because of low performance on default GitHub actions servers.
target-branch: main
namespace: zammad
release-label: zammad
