apiVersion: v2
name: zammad
version: 8.2.2
appVersion: 5.4.0-10
description: Zammad is a web based open source helpdesk/customer support system with many features to manage customer communication via several channels like telephone, facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/main/images/zammad_logo_600x520.png
sources:
  - https://github.com/zammad/zammad
  - https://github.com/zammad/zammad-helm
maintainers:
  - name: monotek
    email: monotek23@gmail.com
  - name: martini
    email: enjoy@zammad.com
dependencies:
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 19.5.10
    condition: zammadConfig.elasticsearch.enabled
  - name: memcached
    version: 6.3.6
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.memcached.enabled
  - name: postgresql
    version: 12.1.15
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.postgresql.enabled
  - name: redis
    version: 17.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.redis.enabled
