apiVersion: v2
name: zammad
version: 13.0.13
appVersion: 6.4.1-64
description: Zammad is a web based open source helpdesk/customer support system with many features to manage customer communication via several channels like telephone, facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/main/images/zammad_logo_600x520.png
sources:
  - https://github.com/zammad/zammad
  - https://github.com/zammad/zammad-helm
maintainers:
  - name: monotek
    email: monotek23@gmail.com
  - name: mgruner
    email: enjoy@zammad.com
dependencies:
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 21.4.8
    condition: zammadConfig.elasticsearch.enabled
  - name: minio
    version: 14.10.5
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.minio.enabled
  - name: memcached
    version: 7.6.5
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.memcached.enabled
  - name: postgresql
    version: 16.4.16
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.postgresql.enabled
  - name: redis
    version: 20.11.2
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.redis.enabled
