apiVersion: v2
name: zammad
version: 3.4.0
appVersion: 3.6.0
description: Zammad is a web based open source helpdesk/customer support system with many features to manage customer communication via several channels like telephone, facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/master/images/zammad_logo_600x520.png
sources:
  - https://github.com/zammad/zammad
  - https://github.com/zammad/zammad-docker-compose
  - https://github.com/zammad/zammad-helm
maintainers:
  - name: monotek
    email: monotek23@gmail.com
  - name: martini
    email: contact@zammad.com
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.10.2
    condition: elasticsearch.enabled
  - name: memcached
    version: 5.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: postgresql
    version: 10.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
