apiVersion: v2
name: zammad
version: 12.3.3
appVersion: 6.3.1-121
description: Zammad is a web based open source helpdesk/customer support system with many features to manage customer communication via several channels like telephone, facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/main/images/zammad_logo_600x520.png
sources:
  - https://github.com/zammad/zammad
  - https://github.com/zammad/zammad-helm
maintainers:
  - name: monotek
    email: monotek23@gmail.com
  - name: mgruner
    email: enjoy@zammad.com
dependencies:
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 19.21.2
    condition: zammadConfig.elasticsearch.enabled
  - name: minio
    version: 13.8.4
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.minio.enabled
  - name: memcached
    version: 6.14.0
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.memcached.enabled
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.postgresql.enabled
  - name: redis
    version: 17.17.1
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.redis.enabled
