apiVersion: v2
name: zammad
version: 6.7.1
appVersion: 5.2.1
description: Zammad is a web based open source helpdesk/customer support system with many features to manage customer communication via several channels like telephone, facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/main/images/zammad_logo_600x520.png
sources:
  - https://github.com/zammad/zammad
  - https://github.com/zammad/zammad-docker-compose
  - https://github.com/zammad/zammad-helm
maintainers:
  - name: monotek
    email: monotek23@gmail.com
  - name: martini
    email: enjoy@zammad.com
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.17.3
    condition: zammadConfig.elasticsearch.enabled
  - name: memcached
    version: 6.0.16
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.memcached.enabled
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.postgresql.enabled
  - name: redis
    version: 16.8.7
    repository: https://charts.bitnami.com/bitnami
    condition: zammadConfig.redis.enabled
