apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zammad.fullname" . }}-railsserver
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
    app.kubernetes.io/component: zammad-railsserver
  annotations:
    {{- include "zammad.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.zammadConfig.railsserver.replicas }}
  selector:
    matchLabels:
      {{- include "zammad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "zammad.podAnnotations" . | nindent 8 }}
        {{- with .Values.zammadConfig.railsserver.podAnnotations }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      labels:
        {{- include "zammad.podLabels" . | nindent 8 }}
        app.kubernetes.io/component: zammad-railsserver
        {{- with .Values.zammadConfig.railsserver.podLabels }}
        {{- toYaml . | nindent 8}}
        {{- end }}
    spec:
      {{- include "zammad.podSpec.deployment" . | nindent 6 }}
      {{- with .Values.zammadConfig.railsserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zammadConfig.railsserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zammadConfig.railsserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- with .Values.zammadConfig.railsserver.sidecars }}
        {{- toYaml . | nindent 8}}
        {{- end }}
        - name: zammad-railsserver
          {{- include "zammad.containerSpec" (merge (dict "containerConfig" .Values.zammadConfig.railsserver) .) | nindent 10 }}
          command:
            - "bundle"
            - "exec"
            - "puma"
            - "-b"
            - "tcp://[::]:3000"
            - "-w"
            - "{{ .Values.zammadConfig.railsserver.webConcurrency }}"
            - "-e"
            - "production"
          env:
            {{- include "zammad.env" . | nindent 12 }}
            {{- include "zammad.env.failOnPendingMigrations" . | nindent 12 }}
          ports:
            - name: railsserver
              containerPort: 3000
          volumeMounts:
            {{- include "zammad.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "zammad.volumes" . | nindent 8 }}
