{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zammad.fullname" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zammad.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "zammad.serviceAccountName" . }}
{{- end -}}
