{{ if and .Values.autoWizard.enabled (not .Values.secrets.autowizard.useExisting)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.autowizardSecretName" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.autowizard.secretKey }}: {{ .Values.autoWizard.config | b64enc | b64enc | quote }}
{{ end }}