{{ if and .Values.autoWizard.enabled (not .Values.secrets.autowizard.useExisting)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.autowizardSecretName" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.autowizard.secretKey }}: {{ .Values.autoWizard.config | b64enc | b64enc | quote }}
{{ end }}
{{ if and .Values.zammadConfig.elasticsearch.pass (not .Values.secrets.elasticsearch.useExisting) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.elasticsearchSecretName" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.elasticsearch.secretKey }}: {{ .Values.zammadConfig.elasticsearch.pass | b64enc | quote }}
{{ end }}
{{ if not .Values.secrets.postgresql.useExisting }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.postgresqlSecretName" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.postgresql.secretKey }}: {{ .Values.zammadConfig.postgresql.pass | b64enc | quote }}
{{ end }}
{{ if and .Values.zammadConfig.redis.pass (not .Values.secrets.redis.useExisting) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.redisSecretName" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.redis.secretKey }}: {{ .Values.zammadConfig.redis.pass | b64enc | quote }}
{{ end }}
