apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.fullname" . }}-postgresql-pass
  labels:
    app.kubernetes.io/name: {{ include "zammad.name" . }}
    helm.sh/chart: {{ include "zammad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgresql-pass: {{ .Values.envConfig.postgresql.pass | b64enc | quote }}
{{- if .Values.autoWizard.enabled  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "zammad.fullname" . }}-autowizard"
  labels:
    app.kubernetes.io/name: {{ include "zammad.name" . }}
    helm.sh/chart: {{ include "zammad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  autowizard: {{ .Values.autoWizard.config | b64enc | b64enc | quote }}
{{ end }}
