apiVersion: v1
kind: Service
metadata:
  name: {{ include "zammad.fullname" . }}-railsserver
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
  annotations:
    {{- include "zammad.annotations" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "zammad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zammad-railsserver
