{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zammad.serviceAccountName" . }}
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
  annotations:
    {{- include "zammad.annotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
