apiVersion: v1
kind: Service
metadata:
  name: {{ include "zammad.fullname" . }}-websocket
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6042
      targetPort: 6042
      protocol: TCP
      name: http
  selector:
    {{- include "zammad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zammad-websocket
