apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "zammad.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "zammad.name" . }}
    helm.sh/chart: {{ include "zammad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zammad.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zammad.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: {{ .Values.image.repository }}:{{if eq .Values.image.repository "zammad/zammad-docker-compose"}}zammad-{{ end }}{{ .Values.image.tag }}
        args: [ "zammad-init" ]
        env:
        {{- if .Values.useElasticsearch }}
        - name: "ELASTICSEARCH_HOST"
          value: {{ .Release.Name }}-elasticsearch-client
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        {{- else }}
        {{- range $key, $value := .Values.externalElasticsearchHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.useMemcached }}
        - name: "MEMCACHED_HOST"
          value: {{ .Release.Name }}-memcached
        - name: "MEMCACHED_PORT"
          value: "11211"
        {{- else }}
        {{- range $key, $value := .Values.externalMemcachedHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.usePostgresql }}
        - name: "POSTGRESQL_HOST"
          value: {{ .Release.Name }}-postgresql
        - name: "POSTGRESQL_PORT"
          value: "5432"
        {{- else }}
        {{- range $key, $value := .Values.externalPostgresHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
      containers:
      - name: {{ .Chart.Name }}-nginx
        image: {{ .Values.image.repository }}:{{if eq .Values.image.repository "zammad/zammad-docker-compose"}}zammad-{{ end }}{{ .Values.image.tag }}
        args: [ "zammad-nginx" ]
        env:
        {{- if .Values.useElasticsearch }}
        - name: "ELASTICSEARCH_HOST"
          value: {{ .Release.Name }}-elasticsearch-client
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        {{- else }}
        {{- range $key, $value := .Values.externalElasticsearchHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.useMemcached }}
        - name: "MEMCACHED_HOST"
          value: {{ .Release.Name }}-memcached
        - name: "MEMCACHED_PORT"
          value: "11211"
        {{- else }}
        {{- range $key, $value := .Values.externalMemcachedHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.usePostgresql }}
        - name: "POSTGRESQL_HOST"
          value: {{ .Release.Name }}-postgresql
        - name: "POSTGRESQL_PORT"
          value: "5432"
        {{- else }}
        {{- range $key, $value := .Values.externalPostgresHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
         - name: {{ template "zammad.fullname" . }}-nginx
           mountPath: /etc/nginx/sites-enabled
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources.nginx | indent 10 }}
      - name: {{ .Chart.Name }}-railsserver
        image: {{ .Values.image.repository }}:{{if eq .Values.image.repository "zammad/zammad-docker-compose"}}zammad-{{ end }}{{ .Values.image.tag }}
        args: ["zammad-railsserver"]
        env:
        {{- if .Values.useElasticsearch }}
        - name: "ELASTICSEARCH_HOST"
          value: {{ .Release.Name }}-elasticsearch-client
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        {{- else }}
        {{- range $key, $value := .Values.externalElasticsearchHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.useMemcached }}
        - name: "MEMCACHED_HOST"
          value: {{ .Release.Name }}-memcached
        - name: "MEMCACHED_PORT"
          value: "11211"
        {{- else }}
        {{- range $key, $value := .Values.externalMemcachedHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.usePostgresql }}
        - name: "POSTGRESQL_HOST"
          value: {{ .Release.Name }}-postgresql
        - name: "POSTGRESQL_PORT"
          value: "5432"
        {{- else }}
        {{- range $key, $value := .Values.externalPostgresHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: railsserver
          containerPort: 3000
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources.railsserver | indent 10 }}
      - name: {{ .Chart.Name }}-scheduler
        image: {{ .Values.image.repository }}:{{if eq .Values.image.repository "zammad/zammad-docker-compose"}}zammad-{{ end }}{{ .Values.image.tag }}
        args: [ "zammad-scheduler" ]
        env:
        {{- if .Values.useElasticsearch }}
        - name: "ELASTICSEARCH_HOST"
          value: {{ .Release.Name }}-elasticsearch-client
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        {{- else }}
        {{- range $key, $value := .Values.externalElasticsearchHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.useMemcached }}
        - name: "MEMCACHED_HOST"
          value: {{ .Release.Name }}-memcached
        - name: "MEMCACHED_PORT"
          value: "11211"
        {{- else }}
        {{- range $key, $value := .Values.externalMemcachedHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.usePostgresql }}
        - name: "POSTGRESQL_HOST"
          value: {{ .Release.Name }}-postgresql
        - name: "POSTGRESQL_PORT"
          value: "5432"
        {{- else }}
        {{- range $key, $value := .Values.externalPostgresHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
        resources:
{{ toYaml .Values.resources.scheduler | indent 10 }}
      - name: {{ .Chart.Name }}-websocket
        image: {{ .Values.image.repository }}:{{if eq .Values.image.repository "zammad/zammad-docker-compose"}}zammad-{{ end }}{{ .Values.image.tag }}
        args: [ "zammad-websocket" ]
        env:
        {{- if .Values.useElasticsearch }}
        - name: "ELASTICSEARCH_HOST"
          value: {{ .Release.Name }}-elasticsearch-client
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        {{- else }}
        {{- range $key, $value := .Values.externalElasticsearchHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.useMemcached }}
        - name: "MEMCACHED_HOST"
          value: {{ .Release.Name }}-memcached
        - name: "MEMCACHED_PORT"
          value: "11211"
        {{- else }}
        {{- range $key, $value := .Values.externalMemcachedHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if .Values.usePostgresql }}
        - name: "POSTGRESQL_HOST"
          value: {{ .Release.Name }}-postgresql
        - name: "POSTGRESQL_PORT"
          value: "5432"
        {{- else }}
        {{- range $key, $value := .Values.externalPostgresHost }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        imagePullPolicy: Always
        ports:
        - name: websocket
          containerPort: 6042
        volumeMounts:
         - name: {{ template "zammad.fullname" . }}
           mountPath: /opt/zammad
        readinessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources.websocket | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: {{ template "zammad.fullname" . }}-nginx
        configMap:
          name: {{ template "zammad.fullname" . }}-nginx
      - name: {{ template "zammad.fullname" . }}
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "zammad.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
